### ISSUE TITLE
Roadblock with Mac

### ISSUE THREAD

**Issue by antkeyes** [cis3296f22/ExcessChess#10]
<img width="906" alt="Screen Shot 2022-10-28 at 12 55 21 PM" src="https://user-images.githubusercontent.com/80372565/198691402-963e4517-f3c6-45dd-87f3-4df17c9b6384.png">

Cannot get past OS choice on Step 3

**Comment by ka-puna** [comment]
The "Identifier" field is required per the first error message.
The other messages are related to app signatures for the macOS closed ecosystem.

Reference: https://docs.godotengine.org/en/stable/tutorials/export/exporting_for_macos.html
