### ISSUE TITLE
Unzip Main Confusion

### ISSUE THREAD

**Issue by antkeyes** [cis3296f22/ExcessChess#7]
- would be helpful to mention that after downloading the main branch it is not necessary to unzip it. We did it manually thinking that we had to and then realized after that it was not necessary.

**Comment by ka-puna** [comment]
The instructions explicitly instructs users to select the ZIP file and does not mention extraction, which is in noticeable contrast to the previous download instruction.

In my experience, adding more details, especially negative statements, tends to confuse users.
