### ISSUE TITLE
Some warning after exporting exe

### ISSUE THREAD

**Issue by timlopesTU** [cis3296f22/ExcessChess#9]
![image](https://user-images.githubusercontent.com/112199199/198687809-a034eb8e-7aea-4b34-8e1e-686f8a0d0863.png)

**Comment by ka-puna** [comment]
This message refers to rcedit, an optional tool to modify Windows executables, for example changing the application icon.

This does not affect functionality, and this responsibility will be fulfilled for by release binaries.

Reference: https://docs.godotengine.org/en/3.5/tutorials/export/changing_application_icon_for_windows.html
